### ISSUE TITLE
fix (test): blocking commit of the dataset

### ISSUE THREAD

**Issue by madvid** [42-AI/SentimentalBB#91]
# Prerequisites

# Expected Behavior

Be able to commit the data.dvc

# Current Behavior

I cannot commit the data.dvc

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run the script to get the dataset
2. `poetry run dvc add data`
3. `git add data.dvc`
4. `git commit -m "message`"

## Context

Please provide any relevant information about your setup. 
This is important in case the issue is not reproducible except for under certain conditions.

STANDARD SETUP

## Failure Logs
![image](https://user-images.githubusercontent.com/37487348/161649610-6ad8b27a-993f-44a4-af9d-dda0e5faff83.png)

**Comment by guillaume-salle** [comment]
I have no error when running `poetry run pytest src` on branch master at this time.

I have also no error when running it on branch 87 wich is based on an earlier version of branch master:
the tests are a bit longer because on the new vesion of master, the test for the roberta model is performed only on the VM of github actions and not anymore on commit hook in local (with a check of an environnement variable of CI CD).

So the error is either from your setu (try running the tests on master), or from the modifications you did on your branch (but they are not commited so I don't have access to it).
